// Phase 8 — auto-notify waitlist email.
//
// Sent by the /api/cron/waitlist-notify cron the moment a slot opens
// that matches a waitlist entry's preferences. Same parchment palette
// as reviewRequest.ts so it reads cleanly in any inbox.
//
// Single big CTA — deep-link straight into the booking wizard with the
// service + barber + date pre-selected. The customer should be one tap
// from confirming the slot they were waiting on.

export interface WaitlistOpeningProps {
  customerName: string;
  barberName: string;
  serviceName: string;
  /** Already-formatted local-time string, e.g. "Tomorrow 2:30 PM" or
   * "Friday, May 23 — 10:00 AM". Generated by formatRelativeSlot
   * upstream so the cron stays free of formatting concerns. */
  whenLabel: string;
  /** Full /book deep-link with ?service=...&barber=... pre-populated. */
  bookUrl: string;
  /** Shop physical address — currently 819 Linden Avenue, Zanesville, OH 43701. */
  shopAddress: string;
  /** Shop phone for footer. */
  shopPhone: string;
}

const COLORS = {
  bg: '#f5efe4',
  card: '#ffffff',
  border: '#e6dccc',
  ink: '#1c1814',
  inkSoft: '#3d362c',
  muted: '#7a6f5f',
  gold: '#a07d30',
  goldLight: '#c9a35c',
  textOnGold: '#1c1814',
};

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function firstName(full: string): string {
  const trimmed = (full ?? '').trim();
  if (!trimmed) return 'friend';
  const space = trimmed.indexOf(' ');
  return space === -1 ? trimmed : trimmed.slice(0, space);
}

export function waitlistOpeningSubject(
  props: Pick<WaitlistOpeningProps, 'whenLabel' | 'barberName'>,
): string {
  return `An opening came up — ${props.whenLabel} with ${props.barberName}`;
}

export function waitlistOpeningHtml(props: WaitlistOpeningProps): string {
  const first = escapeHtml(firstName(props.customerName));
  const barber = escapeHtml(props.barberName);
  const service = escapeHtml(props.serviceName);
  const when = escapeHtml(props.whenLabel);
  const safeBookUrl = escapeHtml(props.bookUrl);
  const address = escapeHtml(props.shopAddress);

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>An opening came up at Modern Classic</title>
  </head>
  <body style="margin:0;padding:0;background:${COLORS.bg};color:${COLORS.ink};font-family:'Helvetica Neue',Arial,sans-serif;">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="background:${COLORS.bg};padding:32px 16px;">
      <tr>
        <td align="center">
          <table role="presentation" width="560" cellspacing="0" cellpadding="0" border="0" style="max-width:560px;background:${COLORS.card};border:1px solid ${COLORS.border};border-radius:8px;overflow:hidden;">
            <tr>
              <td style="padding:32px 36px 16px;text-align:center;border-bottom:1px solid ${COLORS.border};">
                <div style="font-family:Georgia,'Times New Roman',serif;font-size:22px;letter-spacing:0.02em;color:${COLORS.ink};">
                  Modern <span style="color:${COLORS.gold};">·</span> Classic
                </div>
                <div style="margin-top:6px;font-size:11px;letter-spacing:0.18em;text-transform:uppercase;color:${COLORS.muted};">
                  An opening came up
                </div>
              </td>
            </tr>
            <tr>
              <td style="padding:28px 36px 8px;">
                <p style="margin:0 0 14px;font-size:18px;line-height:1.45;color:${COLORS.ink};">
                  Hi ${first} — good news.
                </p>
                <p style="margin:0 0 18px;font-size:16px;line-height:1.55;color:${COLORS.inkSoft};">
                  A slot just opened up that matches the dates and times you put on your waitlist:
                </p>
                <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="margin:0 0 22px;border:1px solid ${COLORS.border};border-radius:6px;background:${COLORS.bg};">
                  <tr>
                    <td style="padding:18px 20px;">
                      <p style="margin:0 0 6px;font-size:13px;letter-spacing:0.16em;text-transform:uppercase;color:${COLORS.gold};font-weight:700;">When</p>
                      <p style="margin:0 0 14px;font-size:18px;color:${COLORS.ink};font-weight:600;">${when}</p>
                      <p style="margin:0 0 6px;font-size:13px;letter-spacing:0.16em;text-transform:uppercase;color:${COLORS.gold};font-weight:700;">Service</p>
                      <p style="margin:0 0 14px;font-size:16px;color:${COLORS.ink};">${service}</p>
                      <p style="margin:0 0 6px;font-size:13px;letter-spacing:0.16em;text-transform:uppercase;color:${COLORS.gold};font-weight:700;">Barber</p>
                      <p style="margin:0;font-size:16px;color:${COLORS.ink};">${barber}</p>
                    </td>
                  </tr>
                </table>
                <table role="presentation" cellspacing="0" cellpadding="0" border="0" style="margin:0 0 18px;">
                  <tr>
                    <td align="center" style="background:${COLORS.gold};border-radius:4px;">
                      <a href="${safeBookUrl}" style="display:inline-block;padding:14px 28px;font-family:'Helvetica Neue',Arial,sans-serif;font-size:14px;font-weight:700;letter-spacing:0.16em;text-transform:uppercase;color:${COLORS.textOnGold};text-decoration:none;">
                        Claim this slot
                      </a>
                    </td>
                  </tr>
                </table>
                <p style="margin:0 0 18px;font-size:13px;line-height:1.55;color:${COLORS.muted};">
                  <strong style="color:${COLORS.inkSoft};">First-come, first-served.</strong>
                  Other people may be on the waitlist for this combo too — if you don't book quickly, this slot can be claimed by someone else.
                </p>
                <p style="margin:0 0 8px;font-size:13px;line-height:1.55;color:${COLORS.muted};">
                  Or copy this link into your browser:
                </p>
                <p style="margin:0 0 8px;font-size:13px;line-height:1.55;word-break:break-all;color:${COLORS.gold};">
                  <a href="${safeBookUrl}" style="color:${COLORS.gold};text-decoration:underline;">${safeBookUrl}</a>
                </p>
              </td>
            </tr>
            <tr>
              <td style="padding:18px 36px 26px;border-top:1px solid ${COLORS.border};text-align:center;">
                <p style="margin:0 0 6px;font-size:12px;line-height:1.6;color:${COLORS.muted};">
                  You're getting this because you joined the waitlist on mdrnclassic.com.
                </p>
                <p style="margin:0;font-size:12px;line-height:1.6;color:${COLORS.muted};">
                  Modern Classic Barbershop &amp; Shave Parlor<br />
                  ${address}
                </p>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>`;
}

export function waitlistOpeningText(props: WaitlistOpeningProps): string {
  const first = firstName(props.customerName);
  return `Hi ${first} — good news.

A slot just opened up that matches the dates and times you put on your waitlist:

  When:    ${props.whenLabel}
  Service: ${props.serviceName}
  Barber:  ${props.barberName}

Claim it here:
${props.bookUrl}

First-come, first-served. Other people may be on the waitlist for this combo — if you don't book quickly, this slot can be claimed by someone else.

You're getting this because you joined the waitlist on mdrnclassic.com.

—
Modern Classic Barbershop & Shave Parlor
${props.shopAddress}`;
}
